// ===== KESF DATA =====
// Real curated data for Azerbaijan — Baku, Ganja, Sheki, Quba

const PLACES_DATA = {
  baku: [
    { id: 1, name: "Firuze Restaurant", category: "restaurant", subcategory: "Azerbaijani Cuisine", city: "baku", address: "Neftchilar Ave 153, Baku", phone: "+994 12 493 2227", rating: 4.7, reviews: 312, price: "$$", tags: ["family", "traditional", "plov"], description: "One of Baku's most beloved traditional Azerbaijani restaurants, famous for authentic plov and dolma. Family-friendly with private rooms available.", hours: "12:00–23:00", image: "🍽️", lat: 40.3698, lng: 49.8360, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600","https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600"] },
    { id: 2, name: "Sumakh Restaurant", category: "restaurant", subcategory: "Azerbaijani Cuisine", city: "baku", address: "Istiqlaliyyat St 8, Baku", phone: "+994 12 492 0123", rating: 4.6, reviews: 245, price: "$$", tags: ["family", "authentic", "kebab"], description: "Classic Azerbaijani cuisine in the heart of old Baku. Try their signature lamb kebab and fresh bread from the tandoor.", hours: "11:00–23:00", image: "🍽️", lat: 40.3665, lng: 49.8367, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1544025162-d76694265947?w=600"] },
    { id: 3, name: "Cinar Restaurant", category: "restaurant", subcategory: "Fine Dining", city: "baku", address: "Bul-Bul Ave 22, Baku", phone: "+994 12 598 7722", rating: 4.8, reviews: 189, price: "$$$", tags: ["romantic", "family", "caspian fish"], description: "Upscale dining with panoramic views of the Caspian Sea. Specializes in fresh Caspian fish dishes and modern Azerbaijani cuisine.", hours: "13:00–00:00", image: "🍽️", lat: 40.3650, lng: 49.8330, verified: true, popular: false, photos: ["https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600"] },
    { id: 4, name: "Mugam Club Restaurant", category: "restaurant", subcategory: "Cultural Dining", city: "baku", address: "Aliaga Vahid 9, Baku", phone: "+994 12 498 0990", rating: 4.5, reviews: 421, price: "$$", tags: ["family", "live music", "mugam", "cultural"], description: "Unique dining experience with live mugam music performances. Authentic Azerbaijani food in a beautifully decorated national style interior.", hours: "12:00–24:00", image: "🎵", lat: 40.3695, lng: 49.8345, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600"] },
    { id: 5, name: "Çay Evi Old City", category: "teahouse", subcategory: "Traditional Tea", city: "baku", address: "İçərişəhər, Kichik Qala St 3, Baku", phone: "+994 55 234 5678", rating: 4.9, reviews: 567, price: "$", tags: ["friends", "tea", "traditional", "backgammon"], description: "Authentic Azerbaijani tea house inside the Old City walls. Perfect for drinking black tea with jam and playing backgammon with friends.", hours: "08:00–22:00", image: "☕", lat: 40.3660, lng: 49.8390, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600"] },
    { id: 6, name: "Nargile Çay Evi", category: "teahouse", subcategory: "Tea & Hookah", city: "baku", address: "Fountain Square Area, Baku", phone: "+994 50 345 6789", rating: 4.4, reviews: 298, price: "$", tags: ["friends", "hookah", "tea", "social"], description: "Popular gathering spot for friends. Serves premium Azerbaijani and Georgian teas alongside hookah. Classic backgammon tables available.", hours: "10:00–02:00", image: "☕", lat: 40.3680, lng: 49.8350, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"] },
    { id: 7, name: "Tofiq Bahramov Stadium", category: "sports", subcategory: "Football Stadium", city: "baku", address: "Hüsü Hacıyev St, Baku", phone: "+994 12 431 4015", rating: 4.3, reviews: 892, price: "$$", tags: ["football", "sports", "family", "friends"], description: "The main football stadium of Azerbaijan, home to the national team. Hosts Qarabağ FK and major international matches. Named after the famous linesman of the 1966 World Cup.", hours: "Match days only", image: "⚽", lat: 40.4089, lng: 49.8671, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600"] },
    { id: 8, name: "Baku Olympic Stadium", category: "sports", subcategory: "Multi-Sports Arena", city: "baku", address: "Olympic Stadium Complex, Baku", phone: "+994 12 480 0000", rating: 4.6, reviews: 1205, price: "$$$", tags: ["sports", "football", "concerts", "events"], description: "Modern 68,700-seat Olympic stadium. Hosted Euro 2020 games and Formula 1 pit lane. State-of-the-art facility for major events in Azerbaijan.", hours: "Event days", image: "🏟️", lat: 40.3820, lng: 49.8494, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600"] },
    { id: 9, name: "Lokomotiv Sports Complex", category: "sports", subcategory: "Sports Club", city: "baku", address: "Lokomotiv St 14, Baku", phone: "+994 12 432 6677", rating: 4.2, reviews: 134, price: "$", tags: ["football", "gym", "family", "sports"], description: "Community sports complex with football pitches, gym facilities, and swimming pool. Popular for weekend football matches with friends.", hours: "07:00–22:00", image: "⚽", lat: 40.3900, lng: 49.8500, verified: true, popular: false, photos: [] },
    { id: 10, name: "Four Seasons Hotel Baku", category: "hotel", subcategory: "5-Star Hotel", city: "baku", address: "1 Neftchilar Ave, Baku", phone: "+994 12 404 2424", rating: 4.9, reviews: 2341, price: "$$$$", tags: ["luxury", "business", "spa", "caspian view"], description: "The most prestigious hotel in Baku, offering stunning Caspian Sea views. Features world-class spa, multiple restaurants, and impeccable service.", hours: "24/7", image: "🏨", lat: 40.3695, lng: 49.8274, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600"] },
    { id: 11, name: "JW Marriott Absheron Baku", category: "hotel", subcategory: "5-Star Hotel", city: "baku", address: "Azadliq Square 2, Baku", phone: "+994 12 490 7777", rating: 4.8, reviews: 1876, price: "$$$$", tags: ["luxury", "business", "central", "family"], description: "Iconic hotel on Azadliq Square with breathtaking Flame Tower views. Excellent business facilities and family-friendly amenities.", hours: "24/7", image: "🏨", lat: 40.3756, lng: 49.8411, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600"] },
    { id: 12, name: "Pullman Baku Hotel", category: "hotel", subcategory: "4-Star Hotel", city: "baku", address: "Tbilisi Ave 27, Baku", phone: "+994 12 404 5000", rating: 4.6, reviews: 987, price: "$$$", tags: ["business", "modern", "rooftop pool"], description: "Contemporary hotel with rooftop infinity pool and panoramic city views. Popular with business travelers and tourists alike.", hours: "24/7", image: "🏨", lat: 40.3620, lng: 49.8480, verified: true, popular: false, photos: [] },
    { id: 13, name: "Lola Bar & Club", category: "nightlife", subcategory: "Nightclub", city: "baku", address: "Nizami St 96, Baku", phone: "+994 50 900 1234", rating: 4.4, reviews: 445, price: "$$$", tags: ["nightclub", "friends", "dancing", "cocktails"], description: "Baku's premier nightclub with international DJs, premium cocktails, and a sophisticated crowd. Dress code enforced on weekends.", hours: "22:00–06:00", image: "🎉", lat: 40.3688, lng: 49.8356, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1571204829887-3b8d69e4094d?w=600"] },
    { id: 14, name: "360 Rooftop Bar", category: "nightlife", subcategory: "Rooftop Bar", city: "baku", address: "Port Baku Mall, Baku", phone: "+994 12 404 3600", rating: 4.7, reviews: 678, price: "$$$", tags: ["rooftop", "cocktails", "views", "friends", "date"], description: "Stunning 360-degree rooftop bar with panoramic Caspian Sea and city views. Best cocktails in Baku with live DJ sets on weekends.", hours: "18:00–03:00", image: "🍹", lat: 40.3720, lng: 49.8280, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600"] },
    { id: 15, name: "Çinar Bar", category: "nightlife", subcategory: "Sports Bar", city: "baku", address: "Hüsü Hacıyev 6, Baku", phone: "+994 12 497 8832", rating: 4.3, reviews: 312, price: "$$", tags: ["sports bar", "friends", "beer", "football"], description: "Lively sports bar with multiple screens for football matches. Great selection of local and imported beers. Packed on match days.", hours: "12:00–02:00", image: "🍺", lat: 40.3710, lng: 49.8380, verified: true, popular: false, photos: [] },
    { id: 16, name: "Baku Zoo", category: "kids", subcategory: "Zoo", city: "baku", address: "U. Hajibeyli St 1, Baku", phone: "+994 12 440 7151", rating: 4.1, reviews: 1234, price: "$", tags: ["kids", "family", "animals", "outdoor"], description: "Baku's main zoo home to over 2,000 animals. Recently renovated with modern enclosures. Perfect half-day family activity.", hours: "09:00–18:00", image: "🦁", lat: 40.3756, lng: 49.8678, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1503656142023-618e7d1f435a?w=600"] },
    { id: 17, name: "Dream Land Amusement Park", category: "kids", subcategory: "Amusement Park", city: "baku", address: "Hazi Aslanov, Baku", phone: "+994 12 450 5050", rating: 4.4, reviews: 2156, price: "$$", tags: ["kids", "family", "rides", "fun"], description: "Azerbaijan's largest amusement park with roller coasters, water park, and entertainment zones. Perfect for families with children of all ages.", hours: "10:00–22:00", image: "🎢", lat: 40.3850, lng: 49.9200, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?w=600"] },
    { id: 18, name: "Baku Aquarium", category: "kids", subcategory: "Aquarium", city: "baku", address: "National Park, Baku", phone: "+994 12 492 0456", rating: 4.2, reviews: 876, price: "$", tags: ["kids", "family", "fish", "educational"], description: "Fascinating aquarium featuring Caspian Sea marine life and exotic species from around the world. Educational and fun for the whole family.", hours: "10:00–19:00", image: "🐠", lat: 40.3680, lng: 49.8400, verified: true, popular: false, photos: [] },
    { id: 19, name: "CinemaPlus Flame Towers", category: "cinema", subcategory: "IMAX Cinema", city: "baku", address: "Flame Towers, Baku", phone: "+994 12 404 1070", rating: 4.6, reviews: 3421, price: "$$", tags: ["movies", "IMAX", "friends", "date", "family"], description: "Azerbaijan's premier IMAX cinema located in the iconic Flame Towers. Latest Hollywood and local films in stunning quality.", hours: "10:00–23:00", image: "🎬", lat: 40.3656, lng: 49.8445, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600"] },
    { id: 20, name: "Park Cinema Crescent", category: "cinema", subcategory: "Multiplex", city: "baku", address: "Crescent Bay Mall, Baku", phone: "+994 12 460 2020", rating: 4.5, reviews: 2876, price: "$$", tags: ["movies", "family", "friends", "VIP"], description: "Modern multiplex with VIP seating options, Dolby surround sound, and the latest international and Azerbaijani films.", hours: "10:00–24:00", image: "🎬", lat: 40.3600, lng: 49.8200, verified: true, popular: true, photos: [] },
    { id: 21, name: "AutoShine Premium Car Wash", category: "carwash", subcategory: "Premium Auto Care", city: "baku", address: "Binagadi Highway 45, Baku", phone: "+994 50 123 4567", rating: 4.5, reviews: 678, price: "$$", tags: ["car wash", "detailing", "quick service"], description: "Premium car wash and detailing service. Full interior/exterior cleaning, ceramic coating, and paint protection available.", hours: "08:00–21:00", image: "🚗", lat: 40.4200, lng: 49.8600, verified: true, popular: false, photos: [] },
    { id: 22, name: "Crystal Auto Spa", category: "carwash", subcategory: "Auto Detailing", city: "baku", address: "Mehsul District, Baku", phone: "+994 55 987 6543", rating: 4.7, reviews: 445, price: "$$$", tags: ["detailing", "hand wash", "ceramic"], description: "Hand car wash specialists with premium ceramic coating services. Used by Baku's luxury car owners for professional auto care.", hours: "09:00–20:00", image: "✨", lat: 40.4100, lng: 49.8700, verified: true, popular: false, photos: [] },
    { id: 23, name: "Baku Eye Ferris Wheel", category: "activity", subcategory: "Attraction", city: "baku", address: "National Park Seafront, Baku", phone: "+994 12 440 3300", rating: 4.5, reviews: 4521, price: "$", tags: ["family", "romantic", "views", "kids"], description: "The iconic 60-meter ferris wheel on Baku's seafront. Spectacular views of the city and Caspian Sea. Great for families and couples.", hours: "10:00–23:00", image: "🎡", lat: 40.3680, lng: 49.8290, verified: true, popular: true, photos: [] },
    { id: 24, name: "Gobustan Rock Art Museum", category: "activity", subcategory: "Museum & Nature", city: "baku", address: "Gobustan, Baku Region", phone: "+994 12 448 0065", rating: 4.8, reviews: 1234, price: "$", tags: ["family", "cultural", "history", "UNESCO"], description: "UNESCO World Heritage Site with 40,000-year-old rock carvings. Interactive museum and outdoor rock art excursions. A must-visit near Baku.", hours: "09:00–18:00", image: "🏛️", lat: 40.1167, lng: 49.3667, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=600"] },
    { id: 25, name: "Bowling City Baku", category: "activity", subcategory: "Bowling & Entertainment", city: "baku", address: "28 May St 8, Baku", phone: "+994 12 598 0808", rating: 4.3, reviews: 876, price: "$$", tags: ["friends", "family", "bowling", "fun"], description: "Modern bowling center with 16 lanes, billiards, arcade games, and a cafe. Perfect entertainment spot for groups and families.", hours: "10:00–02:00", image: "🎳", lat: 40.3790, lng: 49.8550, verified: true, popular: false, photos: [] },
    { id: 26, name: "Baku Crystal Hall Ice Rink", category: "activity", subcategory: "Ice Skating", city: "baku", address: "Crystal Hall, Baku", phone: "+994 12 490 1212", rating: 4.4, reviews: 567, price: "$$", tags: ["family", "kids", "winter sports", "date"], description: "Professional ice rink inside the Crystal Hall. Open year-round with skate rentals, lessons for beginners, and public skating sessions.", hours: "10:00–22:00", image: "⛸️", lat: 40.3590, lng: 49.8190, verified: true, popular: false, photos: [] },
  ],
  ganja: [
    { id: 101, name: "Khan Bagi Restaurant", category: "restaurant", subcategory: "Azerbaijani Cuisine", city: "ganja", address: "Heydar Aliyev Ave 45, Ganja", phone: "+994 22 256 7890", rating: 4.6, reviews: 234, price: "$$", tags: ["family", "traditional", "garden"], description: "Beautiful garden restaurant serving authentic Ganja-style Azerbaijani cuisine. Known for their unique local dishes not found in Baku.", hours: "11:00–23:00", image: "🍽️", lat: 40.6828, lng: 46.3606, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600"] },
    { id: 102, name: "Kapaz Restaurant", category: "restaurant", subcategory: "Local Cuisine", city: "ganja", address: "Javad Khan St, Ganja", phone: "+994 22 255 4321", rating: 4.4, reviews: 302, price: "$$", tags: ["family", "local", "kebab"], description: "Named after the legendary Mount Kapaz, this restaurant serves hearty local dishes loved by Ganja residents for generations.", hours: "10:00–22:00", image: "🍽️", lat: 40.6815, lng: 46.3595, verified: true, popular: true, photos: [] },
    { id: 103, name: "Ganja Çay Evi", category: "teahouse", subcategory: "Traditional Tea", city: "ganja", address: "Old City Center, Ganja", phone: "+994 22 234 5678", rating: 4.8, reviews: 445, price: "$", tags: ["friends", "tea", "traditional"], description: "Historic tea house in Ganja's old quarter. Serves traditional Ganja-style tea with local sweets and pastries.", hours: "07:00–22:00", image: "☕", lat: 40.6850, lng: 46.3580, verified: true, popular: true, photos: [] },
    { id: 104, name: "Nizami Cinema Ganja", category: "cinema", subcategory: "Cinema", city: "ganja", address: "Nizami St 12, Ganja", phone: "+994 22 245 6789", rating: 4.2, reviews: 567, price: "$", tags: ["movies", "family", "friends"], description: "Main cinema in Ganja showing latest Azerbaijani and international films. Recently renovated with modern projection systems.", hours: "10:00–22:00", image: "🎬", lat: 40.6810, lng: 46.3620, verified: true, popular: true, photos: [] },
    { id: 105, name: "Heydar Aliyev Park", category: "activity", subcategory: "Park & Recreation", city: "ganja", address: "Heydar Aliyev Park, Ganja", phone: "+994 22 257 1234", rating: 4.5, reviews: 1234, price: "Free", tags: ["family", "kids", "outdoor", "picnic"], description: "Beautiful city park with walking paths, playgrounds, and green spaces. Perfect for family outings and weekend picnics.", hours: "24/7", image: "🌿", lat: 40.6900, lng: 46.3500, verified: true, popular: true, photos: [] },
    { id: 106, name: "Javad Khan Stadium", category: "sports", subcategory: "Football Stadium", city: "ganja", address: "Stadium St, Ganja", phone: "+994 22 256 0001", rating: 4.3, reviews: 678, price: "$", tags: ["football", "sports", "friends"], description: "Home stadium of Kapaz PFK. Hosts Premier League matches and local football tournaments. Great atmosphere on match days.", hours: "Match days", image: "⚽", lat: 40.6780, lng: 46.3700, verified: true, popular: true, photos: [] },
    { id: 107, name: "Ganja Hotel", category: "hotel", subcategory: "4-Star Hotel", city: "ganja", address: "Heydar Aliyev Ave 1, Ganja", phone: "+994 22 256 7000", rating: 4.4, reviews: 456, price: "$$$", tags: ["business", "comfortable", "central"], description: "The premier hotel in Ganja with comfortable rooms, restaurant serving local cuisine, and excellent business facilities.", hours: "24/7", image: "🏨", lat: 40.6830, lng: 46.3590, verified: true, popular: false, photos: [] },
    { id: 108, name: "Ganja Boutique Hotel", category: "hotel", subcategory: "Boutique Hotel", city: "ganja", address: "City Center, Ganja", phone: "+994 22 245 8800", rating: 4.3, reviews: 198, price: "$$", tags: ["boutique", "cozy", "central"], description: "Charming boutique hotel in the heart of Ganja, offering a warm and personal atmosphere with locally inspired decor.", hours: "24/7", image: "🏨", lat: 40.6820, lng: 46.3610, verified: true, popular: false, photos: [] },
    { id: 109, name: "Bottle House Ganja", category: "activity", subcategory: "Historical Attraction", city: "ganja", address: "Chölük village, near Ganja", phone: "+994 22 234 0000", rating: 4.6, reviews: 876, price: "$", tags: ["family", "cultural", "unique", "history"], description: "Unique historical house built entirely from glass bottles. A remarkable architectural curiosity and must-visit attraction near Ganja.", hours: "09:00–18:00", image: "🏠", lat: 40.6500, lng: 46.4000, verified: true, popular: true, photos: [] },
    { id: 110, name: "Imamzade Complex", category: "activity", subcategory: "Cultural Site", city: "ganja", address: "Imamzade, Ganja", phone: "+994 22 256 2345", rating: 4.7, reviews: 567, price: "Free", tags: ["cultural", "history", "family"], description: "Important religious and cultural complex in Ganja. Beautiful architecture and peaceful grounds, significant to Azerbaijani heritage.", hours: "09:00–19:00", image: "🕌", lat: 40.6870, lng: 46.3560, verified: true, popular: true, photos: [] },
  ],
  sheki: [
    { id: 201, name: "Sheki Saray Restaurant", category: "restaurant", subcategory: "Fine Dining", city: "sheki", address: "Palace Complex, Sheki", phone: "+994 177 44 5556", rating: 4.8, reviews: 456, price: "$$$", tags: ["family", "traditional", "piti", "historic"], description: "Elegant restaurant adjacent to the famous Khan's Palace. Specializes in Sheki's unique cuisine including piti (lamb soup) and pakhlava.", hours: "12:00–22:00", image: "🍽️", lat: 41.1944, lng: 47.1706, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600"] },
    { id: 202, name: "Sheki Khan's Palace", category: "activity", subcategory: "UNESCO Heritage", city: "sheki", address: "Yukhari Bash, Sheki", phone: "+994 177 44 4455", rating: 4.9, reviews: 2341, price: "$", tags: ["family", "cultural", "UNESCO", "history"], description: "UNESCO World Heritage Site. The 18th-century summer palace with stunning stained glass windows (shebeke). The most iconic attraction in Azerbaijan.", hours: "09:00–18:00", image: "🏯", lat: 41.1950, lng: 47.1700, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=600"] },
    { id: 203, name: "Sheki Çay Evi", category: "teahouse", subcategory: "Traditional Tea", city: "sheki", address: "Old Caravanserai, Sheki", phone: "+994 177 44 3322", rating: 4.7, reviews: 678, price: "$", tags: ["friends", "tea", "historic", "silk road"], description: "Tea house set inside a 200-year-old caravanserai on the ancient Silk Road. Atmospheric setting with traditional Sheki tea and sweets.", hours: "08:00–21:00", image: "☕", lat: 41.1930, lng: 47.1720, verified: true, popular: true, photos: [] },
    { id: 204, name: "Sheki Ipek Yolu Hotel", category: "hotel", subcategory: "Boutique Hotel", city: "sheki", address: "Sheki Old Town", phone: "+994 177 44 5000", rating: 4.6, reviews: 345, price: "$$", tags: ["boutique", "historic", "family", "scenic"], description: "Charming boutique hotel in Sheki's old town with mountain views. Perfect base for exploring the Caucasus foothills and Khan's Palace.", hours: "24/7", image: "🏨", lat: 41.1920, lng: 47.1730, verified: true, popular: false, photos: [] },
    { id: 205, name: "Sheki Karavan Hotel", category: "hotel", subcategory: "Heritage Hotel", city: "sheki", address: "Caravanserai Building, Sheki", phone: "+994 177 44 6600", rating: 4.7, reviews: 289, price: "$$$", tags: ["heritage", "romantic", "historic", "luxury"], description: "Sleep in a restored 18th-century Silk Road caravanserai. Unique stone rooms, lush courtyard, and the sound of the Gurjana River nearby.", hours: "24/7", image: "🏨", lat: 41.1935, lng: 47.1715, verified: true, popular: true, photos: [] },
    { id: 206, name: "Sheki Pakhlava Workshop", category: "activity", subcategory: "Food Experience", city: "sheki", address: "Bazaar St 5, Sheki", phone: "+994 177 44 2211", rating: 4.8, reviews: 234, price: "$", tags: ["family", "cultural", "food", "kids"], description: "Watch and learn traditional Sheki pakhlava (baklava) making, the most famous sweet in Azerbaijan. Can purchase boxes to take home.", hours: "09:00–18:00", image: "🍰", lat: 41.1960, lng: 47.1690, verified: true, popular: true, photos: [] },
    { id: 207, name: "Gelersen-Gorersen Fortress", category: "activity", subcategory: "Historical Site", city: "sheki", address: "Sheki Outskirts", phone: "+994 177 44 0000", rating: 4.5, reviews: 456, price: "Free", tags: ["history", "family", "hiking", "views"], description: "Medieval fortress with panoramic views of Sheki valley. The name means 'Come and See' — a challenging but rewarding hike with incredible scenery.", hours: "Dawn–Dusk", image: "🏰", lat: 41.2100, lng: 47.1800, verified: true, popular: true, photos: [] },
    { id: 208, name: "Sheki Bazaar", category: "activity", subcategory: "Market", city: "sheki", address: "Central Market, Sheki", phone: "", rating: 4.6, reviews: 890, price: "$", tags: ["family", "shopping", "local", "food"], description: "Vibrant local market famous for Sheki halva, dried fruits, silk products, and hand-crafted copper items. A sensory feast.", hours: "08:00–17:00", image: "🛒", lat: 41.1940, lng: 47.1710, verified: true, popular: true, photos: [] },
  ],
  quba: [
    { id: 301, name: "Quba Palace Hotel", category: "hotel", subcategory: "Resort Hotel", city: "quba", address: "Quba City Center", phone: "+994 169 24 5678", rating: 4.5, reviews: 234, price: "$$$", tags: ["resort", "family", "mountain", "nature"], description: "The finest hotel in Quba with mountain views, outdoor pool, and restaurant serving local cuisine. Great base for apple picking season.", hours: "24/7", image: "🏨", lat: 41.3611, lng: 48.5136, verified: true, popular: true, photos: [] },
    { id: 302, name: "Tenghi Canyon", category: "activity", subcategory: "Nature & Adventure", city: "quba", address: "Tenghi, Quba District", phone: "+994 169 24 1111", rating: 4.9, reviews: 1234, price: "Free", tags: ["nature", "hiking", "family", "adventure"], description: "Breathtaking canyon with a natural bridge and crystal-clear river. One of Azerbaijan's most spectacular natural attractions. Suitable for families.", hours: "Dawn–Dusk", image: "🏔️", lat: 41.3000, lng: 48.4000, verified: true, popular: true, photos: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600"] },
    { id: 303, name: "Khinalig Village", category: "activity", subcategory: "Cultural Village", city: "quba", address: "Khinalig, Quba District", phone: "+994 169 24 2222", rating: 4.8, reviews: 876, price: "$", tags: ["cultural", "unique", "family", "mountains"], description: "One of the world's oldest continuously inhabited villages at 2,350m altitude. Ancient culture, unique language, and stunning Caucasus scenery.", hours: "Daily", image: "🏘️", lat: 41.1878, lng: 48.1414, verified: true, popular: true, photos: [] },
    { id: 304, name: "Quba Apple Gardens", category: "activity", subcategory: "Agro Tourism", city: "quba", address: "Quba District", phone: "+994 169 24 3333", rating: 4.6, reviews: 567, price: "$", tags: ["family", "kids", "seasonal", "nature", "food"], description: "Famous apple orchards of Quba. Visit during harvest season (Sept-Oct) to pick fresh apples and try local apple products including juice and jam.", hours: "08:00–18:00 (Sept-Oct)", image: "🍎", lat: 41.3600, lng: 48.5000, verified: true, popular: true, photos: [] },
    { id: 305, name: "Quba Çay Evi", category: "teahouse", subcategory: "Traditional Tea", city: "quba", address: "Quba Bazaar Area", phone: "+994 55 456 7890", rating: 4.5, reviews: 345, price: "$", tags: ["friends", "tea", "local", "authentic"], description: "Authentic mountain tea house in Quba's bazaar district. Try local mountain herbal teas and fresh flatbread with honey and butter.", hours: "07:00–20:00", image: "☕", lat: 41.3620, lng: 48.5150, verified: true, popular: false, photos: [] },
    { id: 306, name: "Afurja Waterfall", category: "activity", subcategory: "Nature", city: "quba", address: "Afurja, Quba District", phone: "+994 169 24 4444", rating: 4.7, reviews: 789, price: "Free", tags: ["nature", "family", "hiking", "waterfall"], description: "Spectacular waterfall in the forests near Quba. The 75-meter cascade is one of the highest in Azerbaijan. Refreshing and photogenic.", hours: "Dawn–Dusk", image: "💧", lat: 41.3200, lng: 48.4500, verified: true, popular: true, photos: [] },
    { id: 307, name: "Qudyalchay Restaurant", category: "restaurant", subcategory: "Local Cuisine", city: "quba", address: "Riverside, Quba", phone: "+994 169 24 6789", rating: 4.4, reviews: 234, price: "$", tags: ["family", "local", "riverside", "fresh"], description: "Family restaurant on the banks of the Qudyalchay river. Fresh local produce, mountain trout, and hearty Quba-style meals.", hours: "10:00–21:00", image: "🍽️", lat: 41.3650, lng: 48.5100, verified: true, popular: false, photos: [] },
    { id: 308, name: "Quba Juma Mosque", category: "activity", subcategory: "Cultural Site", city: "quba", address: "Mosque St, Quba", phone: "", rating: 4.6, reviews: 445, price: "Free", tags: ["cultural", "history", "family"], description: "One of the most beautiful mosques in northern Azerbaijan, built in the 19th century. Intricate stonework and a peaceful courtyard.", hours: "Open daily", image: "🕌", lat: 41.3605, lng: 48.5120, verified: true, popular: true, photos: [] },
  ]
};

const CATEGORIES = [
  { id: "restaurant", label: "Restaurants", icon: "🍽️" },
  { id: "teahouse", label: "Tea Houses", icon: "☕" },
  { id: "sports", label: "Football & Sports", icon: "⚽" },
  { id: "hotel", label: "Hotels", icon: "🏨" },
  { id: "nightlife", label: "Nightlife", icon: "🎉" },
  { id: "kids", label: "Kids & Family", icon: "🎢" },
  { id: "cinema", label: "Cinema", icon: "🎬" },
  { id: "carwash", label: "Car Wash", icon: "🚗" },
  { id: "activity", label: "Activities", icon: "🏔️" },
];

const CITIES = [
  { id: "baku", name: "Baku", nameAz: "Bakı", description: "Capital & largest city", population: "2.3M", icon: "🌆" },
  { id: "ganja", name: "Ganja", nameAz: "Gəncə", description: "Azerbaijan's second city", population: "335K", icon: "🏙️" },
  { id: "sheki", name: "Sheki", nameAz: "Şəki", description: "UNESCO Heritage city", population: "65K", icon: "🏯" },
  { id: "quba", name: "Quba", nameAz: "Quba", description: "Mountain & apple capital", population: "100K", icon: "🏔️" },
];
